[package]
name = "jade-ed"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19", features = ["dynamic_linking", "debug", "bevy_dev_tools", "jpeg"] }
bevy_egui = "0.41.1"
bevy-inspector-egui = "0.37"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
